language: r
dist: xenial
sudo: false

env:
  global:
  - MAKEFLAGS="-j 2"

addons:
  apt:
    sources:
      - sourceline: 'ppa:opencpu/jq'
      - sourceline: 'ppa:ubuntugis/ubuntugis-unstable'
    packages:
     - ccache
     - libprotobuf-dev
     - protobuf-compiler
     - libv8-dev
     - libjq-dev
     - libudunits2-dev
     - libproj-dev
     - libgeos-dev
     - libgdal-dev
     - libnetcdf-dev
     - netcdf-bin
     - r-cran-dplyr
     - r-cran-readr
     - r-cran-stringi
     - r-cran-data.table
     - r-cran-bh

r_packages:
  - remotes

branches:
  only:
    - source

cache:
  packages: yes
  directories:
    - $HOME/bin
    
install:
  - R -e "install.packages('remotes')"
  - R -e "install.packages('spDataLarge', repos = 'https://nowosad.github.io/drat/', type = 'source')"
  - R -e "remotes::install_github('geocompr/geocompkg')"

before_script:
  - "Rscript -e 'blogdown::install_hugo()'"

script:
  - "Rscript -e 'blogdown::build_site()'"

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_PAT
  on:
    branch: source
  local_dir: public
  target_branch: master
  