project:
  type: website

website:
  # favicon: logo.png
  # twitter-card: true
  # open-graph: true
  title: "geocompx"
  site-url: https://geocompx.org/
  description: "geocompx hosts free resources on reproducible geographic data analysis, modelling and visualization with open source software"
  navbar:
    left:
      - href: post.qmd
        text: Posts
      - href: r.qmd
        text: R resources
      - href: py.qmd
        text: Python resources
      - href: guestbook.qmd
        text: Guestbook
    right:
      - href: about.qmd
        text: About us
      - icon: twitter
        href: https://twitter.com/hashtag/geocompr
      - icon: mastodon
        href: https://fosstodon.org/tags/geocompr
      - icon: discord
        href: https://discord.gg/PMztXYgNxp
      - icon: rss
        href: post.xml
  page-footer: 
     left: "geocompx, 2023" 
     right:
      - icon: github
        href: https://github.com/geocompx/geocompx.github.io

format:
  html:
    theme: 
      - simplex
      - styles.scss
    toc: true

execute: 
  freeze: auto