project:
  type: website

website:
  title: "geocompx"
  site-url: https://geocompx.org/
  description: "toDo"
  navbar:
    left:
      - href: post.qmd
        text: Posts
      - href: r.qmd
        text: R resources
      - href: py.qmd
        text: Python resources
      - href: guestbook.qmd
        text: Guestbook
    right:
      - icon: github
        href: https://github.com/geocompr/geocompr.github.io
      - icon: twitter
        href: https://twitter.com/hashtag/geocompr
      - icon: rss
        href: feed.xml

format:
  html:
    theme: lumen
    css: styles.css
    toc: true

execute: 
  freeze: auto