baseURL = "https://geocompr.github.io/"
languageCode = "en-us"
title = "the Geocomputation with R website"
theme = "minimal"
# disqusShortname = "username" # delete this to disable disqus comments
googleAnalytics = "UA-99618359-2"

[params]
    author = "Robin Lovelace, Jakub Nowosad, Jannes Muenchow"
    subtitle = "a book on geographic data analysis, visualization and modeling"
    description = "Geocomputation with R is for people who want to analyze, visualize and model geographic data with open source software. It is based on R, a statistical programming language that has powerful data processing, visualization, and geospatial capabilities. The book equips you with the knowledge and skills to tackle a wide range of issues manifested in geographic data, including those with scientific, societal, and environmental implications. This book will interest people from many backgrounds, especially Geographic Information Systems (GIS) users interested in applying their domain-specific knowledge in a powerful open source language for data science, and R users interested in extending their skills to handle spatial data. The online version of the book is hosted at [geocompr.robinlovelace.net](https://geocompr.robinlovelace.net/)."
    githubUsername = "#"
    accent = "#2a0829"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "solarized-dark"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift"]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/post/"
    name = "Posts"
    weight = 2

[[menu.main]]
    url = "/presentations/"
    name = "Presentations"
    weight = 3

[[menu.main]]
    url = "/workshops/"
    name = "Workshops"
    weight = 4
    
[[menu.main]]
    url = "/geocompkg/articles/"
    name = "Vignettes and solutions"
    weight = 5

[[menu.main]]
    url = "/guestbook/"
    name = "Guestbook"
    weight = 6

# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/

 [[menu.icon]]
     url = "https://geocompr.robinlovelace.net/"
     name = "book"
     weight = 1

[[menu.icon]]
    url = "https://github.com/Robinlovelace/geocompr"
    name = "github"
    weight = 2

[[menu.icon]]
    url = "https://twitter.com/hashtag/geocompr"
    name = "twitter"
    weight = 3
    
[[menu.icon]]
    url = "https://geocompr.github.io/feed.xml"
    name = "rss"
    weight = 4

# [[menu.icon]]
#     url = "https://www.linkedin.com/in/username/"
#     name = "linkedin"
#     weight = 4

# [[menu.icon]]
#     url = "https://www.stackoverflow.com/username/"
#     name = "stack-overflow"
#     weight = 5

[outputs]
home = [ "RSS", "HTML"]
section  = ["HTML"]

[outputFormats]
[outputFormats.RSS]
mediatype = "application/rss"
baseName = "feed"